#ifndef DEPENDENCYRESOLVER_GLOBAL_H
#define DEPENDENCYRESOLVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DEPENDENCYRESOLVER_LIBRARY)
#  define DEPENDENCYRESOLVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DEPENDENCYRESOLVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DEPENDENCYRESOLVER_GLOBAL_H
