#ifndef QTDEPENDENCYRESOLVERTESTSBLLNATIVE_GLOBAL_H
#define QTDEPENDENCYRESOLVERTESTSBLLNATIVE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTDEPENDENCYRESOLVERTESTSBLLNATIVE_LIBRARY)
#  define QTDEPENDENCYRESOLVERTESTSBLLNATIVESHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTDEPENDENCYRESOLVERTESTSBLLNATIVESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTDEPENDENCYRESOLVERTESTSBLLNATIVE_GLOBAL_H
