#ifndef QTDEPENDENCYRESOLVERTESTSBLL_GLOBAL_H
#define QTDEPENDENCYRESOLVERTESTSBLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTDEPENDENCYRESOLVERTESTSBLL_LIBRARY)
#  define QTDEPENDENCYRESOLVERTESTSBLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTDEPENDENCYRESOLVERTESTSBLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTDEPENDENCYRESOLVERTESTSBLL_GLOBAL_H
