#ifndef QTDEPENDENCYRESOLVERTESTSDAL_GLOBAL_H
#define QTDEPENDENCYRESOLVERTESTSDAL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTDEPENDENCYRESOLVERTESTSDAL_LIBRARY)
#  define QTDEPENDENCYRESOLVERTESTSDALSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTDEPENDENCYRESOLVERTESTSDALSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTDEPENDENCYRESOLVERTESTSDAL_GLOBAL_H
